name: Windows
on: 
  push:
    paths:
      - 'example/**'
      - 'FluentUI/**'
      - '.github/workflows/windows.yml'
  pull_request:
    paths:
      - 'example/**'
      - 'FluentUI/**'
      - '.github/workflows/windows.yml'
      
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        include:
          - qt_ver: 6.5.3        
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64  
    env:
      targetName: example.exe
      fileName: example
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
             
      - name: install env   
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          msvcArch: ${{ matrix.msvc_arch }}          
        shell: pwsh
        run: |
          pip install mako
          pip install PySide6-FluentUI-QML
          pip install pyinstaller
          
      - name: package  
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          msvcArch: ${{ matrix.msvc_arch }}          
        shell: pwsh
        run: |
          python ./Scripts/qrc2py.py ./example/resource/example.qrc ./example/resource/example_rc.py
          python ./Scripts/genversion.py
          pyinstaller -y ./example/main.spec
  
      - uses: actions/upload-artifact@v2
        if: startsWith(github.event.ref, 'refs/tags/') == false
        with:
          name: ${{ env.fileName }}_${{ matrix.qt_arch }}_PySide6
          path: dist

      - name: inno setup install
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: zhuzichu520/inno-setup-action@v1.0.1
        with:
          filepath: ./action-cli/InstallerScript.iss

      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./action-cli/installer.exe
          asset_name: ${{ env.fileName }}_${{ github.ref_name }}_${{ matrix.qt_arch }}_PySide6.exe
          tag: ${{ github.ref }}
          overwrite: true     

